spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tecnoscloud_db?createDatabaseIfNotExist=true
    username: root
    password: root
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logs:
  destination: logstash:3100

file:
  baseUrl: https://89.33.44.227

